elasticsearch:
    image: ahri/elasticsearch:0.0.1

logstash:
    image: ahri/logstash:0.0.1

    links:
        - elasticsearch

    ports:
        - 12201:12201

    command: -e 'input { gelf {} } output { elasticsearch { hosts => elasticsearch } }'

kibana:
    image: ahri/kibana:0.0.1

    links:
        - elasticsearch

    ports:
        - 5601:5601

    command: "--elasticsearch http://elasticsearch:9200"
